port: 80
db:
  driver: "mysql"
  username: "user"
  password: "user"
  name: "app"
  net: tcp
  host: mysql
  port: 3306
rules:
  - path: /show/:id/
    query: "SELECT * FROM test WHERE id = {{id}};"
  - path: /showall/
    query: SELECT * FROM test;
  - path: /create/
    query: INSERT INTO test (body) VALUES ({{body}});
